### ISSUE TITLE
Dúvida 

### ISSUE THREAD

**Issue by Wallacewss2033** [Bamaq-Consorcio/teste-backend#1]
O sorteio por rodada é feito de quanto em quanto tempo?

**Comment by tgbamaq** [comment]
O intervalo de sorteio é de 7 rodadas.
Em um periodo de 7 rodadas um morador nao pode ter a mesma vaga
EX. se um morador tem a vaga numero 20 ele so podera ter essa vaga novamente depois de 7 rodadas

**Comment by Wallacewss2033** [comment]
Mas, a rodada é quanto em quanto tempo?
Ou um morador vai ficar na mesma vaga por 7 dias?

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tgbamaq** [comment]
Um morador usa uma vaga por dia
